# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddosify < Formula
  desc "High-performance load testing tool, written in Golang."
  homepage "https://ddosify.com"
  version "0.7.3"
  license "AGPL-3.0-only"

  on_macos do
    url "https://github.com/ddosify/ddosify/releases/download/v0.7.3/ddosify_0.7.3_macos_all.tar.gz"
    sha256 "9461800e2c9c64b1137ff9bf7fb3c7a630da8c7a5a2b373b7c69df8beef46909"

    def install
      bin.install "ddosify"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ddosify/ddosify/releases/download/v0.7.3/ddosify_0.7.3_linux_armv6.tar.gz"
      sha256 "b708e40c9154ca8a3faaa0c8fdb3fe64d7e0f9b1c20b0488bbbf740d892b0e43"

      def install
        bin.install "ddosify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddosify/ddosify/releases/download/v0.7.3/ddosify_0.7.3_linux_arm64.tar.gz"
      sha256 "56e0552eeb436a6d96328b2827c40642a346bbd737af53bf91ea8018c2973cdc"

      def install
        bin.install "ddosify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ddosify/ddosify/releases/download/v0.7.3/ddosify_0.7.3_linux_amd64.tar.gz"
      sha256 "bc9090827a882e061351d35c72c915f18b09fc6fe2cb3c6f3f4a0b091275ee6f"

      def install
        bin.install "ddosify"
      end
    end
  end

  depends_on "go" => :optional

  test do
    system "#{bin}/ddosify --help"
  end
end
