# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddosify < Formula
  desc "High-performance load testing tool, written in Golang."
  homepage "https://ddosify.com"
  version "0.16.0"
  license "AGPL-3.0-only"

  depends_on "go" => :optional

  on_macos do
    url "https://github.com/ddosify/ddosify/releases/download/v0.16.0/ddosify_0.16.0_macos_all.tar.gz"
    sha256 "459ef9f6b18636bb3e1901ae90ba409868e25f17a5ae7d6d4f227be8a4a8586c"

    def install
      bin.install "ddosify"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ddosify/ddosify/releases/download/v0.16.0/ddosify_0.16.0_linux_amd64.tar.gz"
      sha256 "c1ecbd085d826293a49f22f9ad96b84eb22cad9ffc569236c9587f218d98b412"

      def install
        bin.install "ddosify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddosify/ddosify/releases/download/v0.16.0/ddosify_0.16.0_linux_arm64.tar.gz"
      sha256 "b269cefe4b667449bdac269253b6a955716c8f23f3ebcd57922acadbc161ecf3"

      def install
        bin.install "ddosify"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ddosify/ddosify/releases/download/v0.16.0/ddosify_0.16.0_linux_armv6.tar.gz"
      sha256 "fa2f3c5316cfa334b8b25ee8b755ac661536a7b38b876d97c1fc8bd10d03e701"

      def install
        bin.install "ddosify"
      end
    end
  end

  test do
    system "#{bin}/ddosify --help"
  end
end
