# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddosify < Formula
  desc "High-performance load testing tool, written in Golang."
  homepage "https://ddosify.com"
  version "1.0.3"
  license "AGPL-3.0-only"

  depends_on "go" => :optional

  on_macos do
    url "https://github.com/ddosify/ddosify/releases/download/v1.0.3/ddosify_1.0.3_macos_all.tar.gz"
    sha256 "34dd713cda878dbefdbe7d08ad4a30015c734a26fc7d616fe912bb0426899546"

    def install
      bin.install "ddosify"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ddosify/ddosify/releases/download/v1.0.3/ddosify_1.0.3_linux_armv6.tar.gz"
      sha256 "a8e2afb603b21568f6b3f07dcd48232f7ebc7fd5987b92567e809da042dbbc1b"

      def install
        bin.install "ddosify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ddosify/ddosify/releases/download/v1.0.3/ddosify_1.0.3_linux_amd64.tar.gz"
      sha256 "8c21b62bdbcd1f2cae3dd5afa4dbc6fc62cab68bf4cd826557f970c01a3993b5"

      def install
        bin.install "ddosify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddosify/ddosify/releases/download/v1.0.3/ddosify_1.0.3_linux_arm64.tar.gz"
      sha256 "11000a573888dd4b1193d7530bcc0278a48902f0d92be00450360cc53cf4d994"

      def install
        bin.install "ddosify"
      end
    end
  end

  test do
    system "#{bin}/ddosify --help"
  end
end
